
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_INPUT_EGISTEC_320) += et320-int.o
obj-$(CONFIG_INPUT_EGISTEC_320) += navi_input.o
# navi_input.o

