obj-y					+= vipx-debug.o
obj-y					+= vipx-binary.o
obj-y					+= vipx-time.o
obj-y					+= vipx-taskmgr.o
obj-y					+= vipx-graph.o
obj-y					+= vipx-graphmgr.o
obj-y					+= vipx-queue.o
obj-y					+= vipx-vertex.o
obj-y					+= vipx-device.o
obj-y					+= vipx-memory.o
obj-y					+= vipx-system.o
obj-y					+= vipx-io.o
obj-$(CONFIG_EXYNOS_VIPX_INTERFACE)	+= interface/
obj-$(CONFIG_EXYNOS_VIPX_PLATFORM)	+= platform/

EXTRA_CFLAGS += -Idrivers/vision/include -Idrivers/vision/vipx/include
