obj-$(CONFIG_ARCH_EXYNOS)       += exynos-el3_mon.o
obj-$(CONFIG_ARCH_EXYNOS)       += exynos-smc.o

# CAL
obj-$(CONFIG_CAL_IF)		+= cal-if/

obj-$(CONFIG_ECT)		+= ect_parser.o

obj-$(CONFIG_EXYNOS_PMU)	+= exynos-pmu.o

obj-$(CONFIG_EXYNOS_PMU_ARM_DRIVERS)	+= exynos3250-pmu.o exynos4-pmu.o \
					exynos5250-pmu.o exynos5420-pmu.o
obj-$(CONFIG_EXYNOS_PM_DOMAINS) += pm_domains.o

obj-$(CONFIG_EXYNOS_CHIPID)	+= exynos-chipid.o
