obj-$(CONFIG_CAMERA_EEPROM_SELECT) += fimc-is-sensor-eeprom.o
obj-$(CONFIG_CAMERA_EEPROM_GM1_OBJ) += fimc-is-sensor-eeprom-gm1.o

ccflags-y := -Idrivers/media/platform/exynos/fimc-is2
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2/include
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2/vendor
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2/hardware/api
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2/sensor
ccflags-y += -Idrivers/media/platform/exynos/fimc-is2/sensor/module_framework
